compile:	main.o readFile.o QSort.o imple.o
	gcc -g imple.o main.o QSort.o readFile.o -o test

run:
	./test

main.o: main.c
	gcc -c -g main.c

readFile.o:	readFile.c
	gcc -c -g readFile.c

imple.o:	imple.c
	gcc -c -g imple.c

QSort.o:	QSort.c
	gcc -c -g QSort.c
